Add: animal info
Endorze/Group-assignment3 pull request #1
Opened 2024-11-20 16:53 UTC by maysunktong

An Object of animal info

2024-11-20 17:00 UTC, Endorze requested changes
Fix the error on line 36 to avoid syntax error, otherwise the code looks amazing!

2024-11-20 17:00 UTC, Endorze commented on animal-info.js
> +    echidna: {
You have an extra open bracket without a corresponding closing bracket. This mismatch will cause a syntax error and prevent the code from running correctly when we try to use this list of objects, remove and resubmit. Line 36.

2024-11-20 17:44 UTC, Endorze approved these changes
Looks fine!

2024-11-21 13:22 UTC, maysunktong commented
I have add few more animals to be 6 animals of each category. Also, put each data in a more suitable type.

2024-11-21 13:32 UTC, Endorze approved these changes
Looks great!

2024-11-21 14:02 UTC, maysunktong commented
Change lifespan, length, weight back to [string].

2024-11-21 15:18 UTC, mvic89 reviewed
Looks good! nothing seems to be out of order.

2024-11-21 15:19 UTC, mvic89 approved these changes

2024-11-21 15:46 UTC, merged